config/routes.rb
Revelradio::Application.routes.draw do
  get "songs/create"

  get "streams/new"

  get "streams/show"

  get "streams/update"

  post "streams/time"

  match 'streams/time', to: 'streams#time'

  match 'songs/pull', to: 'songs#pull_info'

  get "pages/home"

  get "pages/about"

  get "pages/terms"

  root to: 'streams#new'
  match '/about', to: 'pages#about'
  match '/terms', to: 'pages#terms'

  resources :streams do
    resources :songs
  end

  get '/*words' => 'streams#show'

end

app/models/stream.rb
# == Schema Information
#
# Table name: streams
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  last_used         :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  current_song_time :integer
#

class Stream < ActiveRecord::Base
  attr_accessible :last_used, :name, :current_song_time	

  has_many :songs, dependent: :destroy

  

end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  def new
  	@stream = Stream.new
  end
  
  def create
  	@stream = Stream.new(params[:stream])
  	@stream.name = get_unique_name(@stream.id, Stream.all)
  	if @stream.save
      cookies.delete :dj
      cookies[:dj] = @stream.id
  		redirect_to ('/' + @stream.name)
  	else
  		render 'new'
  	end
  end

  def show
  	@stream = Stream.where(:name => params[:words]).first
    @songs = @stream.songs
    @song = @songs.build
  end

  def destroy
  	@stream = Stream.find(params[:id])
  	@stream.destroy
  	redirect_to root_path
  end

  def time
    @stream = Stream.find(params[:id])
    @time = params[:current_song_time]
    @stream.current_song_time = @time
    @stream.save
    render :json => @stream.current_song_time
  end

end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/streams/_form.html.erb
<%= form_for @stream do |f| %>
	<h3 class="start btn btn-orange textcenter"><%= f.submit 'Start Your Stream'%></h3>
<% end %>

app/views/streams/_song_player.html.erb
<div id="jquery_jplayer_1" class="jp-jplayer"></div>

<div id="jp_container_1" class="jp-audio">
    <div class="jp-type-single">
        <div class="jp-gui jp-interface">
            <ul class="jp-controls">
                
                <!-- comment out any of the following <li>s to remove these buttons -->
                
                <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
            </ul>
            
            <!-- you can comment out any of the following <div>s too -->
            
            <div class="jp-progress">
                <div class="jp-seek-bar">
                    <div class="jp-play-bar"></div>
                </div>
            </div>
            <div class="jp-volume-bar">
                <div class="jp-volume-bar-value"></div>
            </div>
            <div class="jp-current-time"></div>
            <div class="jp-duration"></div>                   
        </div>
        <div class="jp-title">
            <ul>
                <li>Cro Magnon Man</li>
            </ul>
        </div>
        <div class="jp-no-solution">
            <span>Update Required</span>
            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
        </div>
    </div>
</div>

app/views/streams/new.html.erb
<%= render 'streams/form' %>
<p class="textcenter center"><small>Make a radio station, share the link with your buds, listen, get out of here and go do other stuff.</small></p>

app/views/streams/show.html.erb
<div id="album_info">
	<h3>Now Playing:</h3>
	<%= image_tag '/assets/record.png', :id=>"song_artwork", :class=>"album_art" %>
	<p id="track">Finding track...</p>
	<p id="album">Finding album...</p>
	<p id="artist">Finding artist...</p>
	<%= javascript_tag do %>
		song_links = new Array();
		song_ids = new Array();
	<% end %>
	<% @songs.each do |song| %>
	 	<% if song.music_file.url != '/music_files/original/missing.png' %>
	 	<div class="dev">
			<p><%= song.music_file_file_name %> - <%= link_to "Drop", stream_song_path(@stream,song), method: :delete, :id => song.id %></p>
			<audio id='song_<%=song.id %>' src=<%= song.music_file.url %> controls>
			<p>If you are reading this, it is because your browser does not support the audio element.</p>
			</audio>
			<%#=render 'streams/song_player' %>
			<%= javascript_tag do %>
				song_links.push("<%=song.music_file.url%>");
				song_ids.push("<%=song.id%>");
				$('#song_<%=song.id%>').bind('ended', function(){
			    $('#song_<%=song.id+1%>').get(0).play();
			    song_ids.splice(0, 1);
			    $.ajax ({
			    	type: "DELETE",
			    	url: "<%=stream_song_path(@stream, song)%>"
			  	});
				});
			<% end %>
			</div>
		<% end %>
	<% end %>
	<%= javascript_tag do %>
		console.log(song_ids[0]);
		console.log(song_links[0]);
	<% end %>
</div>
<% if cookies[:dj] %>
	<div id="upload_box">
		<%= render 'songs/form' %>
	</div>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){
  	beginner = '#song_';
  	grab_id = beginner + song_ids[0];
		$(grab_id).bind('canplay', function(){
			$(this).get(0).currentTime="<%=@stream.current_song_time%>";
		});
  	$(grab_id).get(0).play();
  	console.log('go!');
  	console.log(song_ids[0]);

  	$.post("/songs/pull", { id: song_ids[0] })
  	.done(function(data) {
  		console.log(data);
  		$('#track').text(data['title']);
  		$('#artist').text(data['artist']);
  		$('#song_artwork').attr("src",data['release_image']);
  		$('#album').text(data['album_name']);
  		$('#track_download_url').text(data['track_download_url']);

  	});

  	var int=self.setInterval(function(){
  		console.log(song_ids);
  		update_current_time(beginner+song_ids[0], "<%=@stream.id%>")}, 1000);
  });
	function update_song_list(){
		song_links.length = 0;
		"<% @songs.each do |song| %> "
			"<% if song.music_file.url != '/music_files/original/missing.png' %>"
				song_links.push("<%=song.music_file.url%>");
			"<% end %>"
		"<%end%>"
		return song_links;
	}

	function update_current_time(grab_id, id_s){
		time_r = $(grab_id).get(0).currentTime;
		console.log($(grab_id).get(0).currentTime);
		$.post("/streams/time", { id: id_s, current_song_time: time_r })
		.done(function(data) {
			console.log(data);
		});
		
	}
	
	function play_next_song(id){
		
	}
</script>

app/views/streams/time.html.erb
<p><%=@stream%> <%=@time%> <%=@stream.current_song_time %> stuff is here</p>